### ISSUE TITLE
Hyper links are parsed incorrectly

### ISSUE THREAD

**Issue by MackenzieMolloy** [brussell98/discord-markdown#25]
Discord-Markdown: 2.5.0

\[TEXT](URL) ---> \[TEXT](\<a href="URL">URL\</a>)

**Comment by MackenzieMolloy** [comment]
I realise now why it does what it does, **discord-markdown** is making basic URLs clickable and doesn't have support for embedded hyperlinks where the format is [TEXT](URL).

**Comment by brussell98** [comment]
Working as intended. Discord only allows links in embeds. To enable embed features use `markdown.toHTML('[label](http://example.com)', { embed: true })`
