### ISSUE TITLE
Add new parser.

### ISSUE THREAD

**Issue by typhoon11** [brussell98/discord-markdown#31]
It's not parsing hyperlinks, it should be added. It's a basic Markdown feature

**Comment by brussell98** [comment]
https://github.com/brussell98/discord-markdown/blob/master/test/single.test.js#L43

Links are parsed. I just confirmed by running the tests.

**Comment by typhoon11** [comment]
Hyperlinks aren't converted
![image](https://user-images.githubusercontent.com/66431066/154832958-523a1277-38fd-49e0-92c5-8b8cb59c8e2a.png)

**Comment by brussell98** [comment]
Yes, because you are not using embed mode. Named links are not allowed in normal messages.

**Comment by typhoon11** [comment]
What do you mean embed mode?

**Comment by typhoon11** [comment]
![image](https://user-images.githubusercontent.com/66431066/154978785-e9b45be5-fd9f-4fe1-bd31-262825020e87.png)
The playground is also not showing, and have some respect towards the user who is reporting an issue, you are just keen to mark an issue closed.

**Comment by brussell98** [comment]
https://github.com/brussell98/discord-markdown#options ...
