### ISSUE TITLE
links are unpercise

### ISSUE THREAD

**Issue by noblockhit** [brussell98/discord-markdown#34]
When using the following `[Link](https://discord.gg/Jpu---------)`  the expected output would be a blue font paragraph, with the content `Link`:
![image](https://user-images.githubusercontent.com/67117651/169602456-0d18bd02-fcb4-469e-95f0-a021435092f1.png)
This just doesn't happen at all. Insted, this is the result:
![image](https://user-images.githubusercontent.com/67117651/169602639-e121c698-a22c-4789-ae45-501d86e9029e.png)

**Comment by brussell98** [comment]
Are you rendering in embed mode? Links are not a normal part of Discord markdown

**Comment by noblockhit** [comment]
oh uhm, how do you do that?

**Comment by noblockhit** [comment]
nvm i found it out, for future questions:
```javascript
var options = {
    "embed": true
}
HTMLOBJECT.innerHTML = discordMarkdown.toHTML(CONTENT, options);
```
